services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb-boards
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    networks:
      - boards_network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data-boards
  mongodb-log:
    driver: local
    name: mongo-log-boards

networks:
  boards_network:
    driver: bridge
    name: boards_network
